FROM ghcr.io/epicgames/unreal-engine:dev-4.27

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        # needed in setup and build scripts:
        wget \
        cmake \
        rsync \
        # from setup.sh:
        clang-9 \
        clang++-9 \
        libc++-9-dev \
        libc++abi-9-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

USER ue4